
# This Gui file was generated by the Tkinter Designer by Parth Jadhav and modified by Justin Gomez
# Design made by Justin Gomez
# https://github.com/ParthJadhav/Tkinter-Designer

import sys
import subprocess
from pathlib import Path
# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Frame, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\jgome\OneDrive\Desktop\Projects\SpendingTracker\build\assets\frame0")
def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

OUTPUT_PATH1 = Path(__file__).parent
ASSETS_PATH1 = OUTPUT_PATH1 / Path(r"C:\Users\jgome\OneDrive\Desktop\Projects\SpendingTracker\build\assets\frame1")
def relative_to_assets1(path1: str) -> Path:
    return ASSETS_PATH1/ Path(path1)


# Main Window Setup ---------------------------------------------------------------
window = Tk()
window.geometry("800x600")
window.configure(bg = "#2E2E2E")

# Main frame Setup --------------------------------------------------------
main_frame = Frame(window, bg="#2E2E2E")
main_frame.pack(fill="both", expand=True)
window.title("Expenses Tracker")
# Set the icon of the window (optional)
# window.iconbitmap("path_to_icon.ico")  # Uncomment and set path if you have an icon

# Functions
def open_income_canvas():
    main_frame.pack_forget()
    income_frame.pack(fill="both", expand=True)

def return_to_main():
    income_frame.pack_forget()
    main_frame.pack(fill="both", expand=True)
    # Update the income balance text
    # main_canvas.itemconfig(income_balance, text="$0.00")  # Example update, replace with actual logic

# Canvas Setup ------------------------------------------------------------------------
main_canvas = Canvas(
    main_frame,
    bg = "#2E2E2E",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
main_canvas.place(x = 0, y = 0)



# Header Text -------------------------------------------------------------------------
main_canvas.create_text(
    215.0,
    15.0,
    anchor="nw",
    text="EXPENSES TRACKER",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 35 * -1)
)



# Income Components ---------------------------------------------------------------------
bg_income = PhotoImage(
    file=relative_to_assets("bg_income.png"))
income_background = main_canvas.create_image(
    227.0,
    105.0,
    image=bg_income
)

main_canvas.create_text(
    120.0,
    80.0,
    anchor="nw",
    text="Income:",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 25 * -1)
)
income_balance = main_canvas.create_text(
    240.0,
    77.0,
    anchor="nw",
    text="$0.00",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 35 * -1)
)



# Expenses Components -------------------------------------------------------------------
bg_expenses = PhotoImage(
    file=relative_to_assets("bg_expenses.png"))
expenses_background = main_canvas.create_image(
    572.0,
    105.0,
    image=bg_expenses
)
main_canvas.create_text(
    460.0,
    80.0,
    anchor="nw",
    text="Expenses:",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 25 * -1)
)
main_canvas.create_text(
    600.0,
    77.0,
    anchor="nw",
    text="$0.00",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 35 * -1)
)



# Balance Components ------------------------------------------------------------------
bg_balance = PhotoImage(
    file=relative_to_assets("bg_balance.png"))
balance_background = main_canvas.create_image(
    400.0,
    180.0,
    image=bg_balance
)

main_canvas.create_text(
    250.0,
    155.0,
    anchor="nw",
    text="Balance:",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 30 * -1)
)
main_canvas.create_text(
    425.0,
    152.0,
    anchor="nw",
    text="$0.00",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 40 * -1)
)



# Image -----------------------------------------------------------------------------------
image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = main_canvas.create_image(
    214.0,
    399.0,
    image=image_image_4
)




# Buttons: New income, expense, and history ------------------------------------------------
# New Income Button
income_button_image = PhotoImage(
    file=relative_to_assets("button_new_income.png"))

new_income_button = Button(
    main_canvas,
    image=income_button_image,
    borderwidth=0,
    highlightthickness=0,
    command=open_income_canvas,  # Open gui1.py when clicked
    #command=lambda: print("button_1 clicked"),  # For testing
    relief="flat",
    bg="#2E2E2E",
    activebackground="#2E2E2E"
)

new_income_button.place(
    x=425.0,
    y=277.0,
)


# New Expense Button
expense_button_image = PhotoImage(
    file=relative_to_assets("button_new_expense.png"))
new_expense_button = Button(
    main_canvas,
    image=expense_button_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat",
    bg="#2E2E2E",
    activebackground="#2E2E2E"
)
new_expense_button.place(
    x=425.0,
    y=366.0,
)


# History Button
history_button_image = PhotoImage(
    file=relative_to_assets("button_history.png"))
history_button = Button(
    main_canvas,
    image=history_button_image,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat",
    bg="#2E2E2E",
    activebackground="#2E2E2E"
)
history_button.place(
    x=425.0,
    y=451.0,
)






# Income Frame Setup ---------------------------------------------------------------
income_frame = Frame(window, bg="#2E2E2E")
income_canvas = Canvas(
    income_frame,
    bg = "#2E2E2E",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)
income_canvas.place(x = 0, y = 0)


entry_image_1 = PhotoImage(
    file=relative_to_assets1("entry_1.png"))
entry_bg_1 = income_canvas.create_image(
    394.5,
    463.0,
    image=entry_image_1
)
entry_1 = Entry(
    income_canvas,
    bd=0,
    bg="#23A127",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=78.0,
    y=440.0,
    width=633.0,
    height=44.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets1("entry_2.png"))
entry_bg_2 = income_canvas.create_image(
    214.5,
    364.0,
    image=entry_image_2
)
entry_2 = Entry(
    income_canvas,
    bd=0,
    bg="#23A127",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=78.0,
    y=341.0,
    width=273.0,
    height=44.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets1("entry_3.png"))
entry_bg_3 = income_canvas.create_image(
    196.5,
    269.0,
    image=entry_image_3
)
entry_3 = Entry(
    income_canvas,
    bd=0,
    bg="#23A127",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=78.0,
    y=246.0,
    width=237.0,
    height=44.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets1("entry_4.png"))
entry_bg_4 = income_canvas.create_image(
    196.5,
    174.0,
    image=entry_image_4
)
entry_4 = Entry(
    income_canvas,
    bd=0,
    bg="#23A127",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=78.0,
    y=151.0,
    width=237.0,
    height=44.0
)

income_canvas.create_text(
    36.0,
    114.0,
    anchor="nw",
    text="Date:",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 30 * -1)
)

income_canvas.create_text(
    39.0,
    211.0,
    anchor="nw",
    text="Category:",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 30 * -1)
)

income_canvas.create_text(
    55.0,
    401.0,
    anchor="nw",
    text="Description",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 30 * -1)
)

income_canvas.create_text(
    33.0,
    306.0,
    anchor="nw",
    text="Amount:",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 30 * -1)
)

income_canvas.create_text(
    248.0,
    36.0,
    anchor="nw",
    text="New Income",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 50 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets1("image_1.png"))
image_1 = income_canvas.create_image(
    592.0,
    269.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets1("button_1.png"))
button_1 = Button(
    income_canvas,
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=return_to_main,
    relief="flat"
)
button_1.place(
    x=233.0,
    y=508.0,
    width=333.814697265625,
    height=60.0
)
# Run the application
#window.resizable(False, False)
window.mainloop()
