
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\jgome\OneDrive\Desktop\Projects\SpendingTracker\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("800x600")
window.configure(bg = "#2E2E2E")


canvas = Canvas(
    window,
    bg = "#2E2E2E",
    height = 600,
    width = 800,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    394.5,
    461.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#CA3D3D",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=78.0,
    y=438.0,
    width=633.0,
    height=44.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    214.5,
    362.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#CA3D3D",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=78.0,
    y=339.0,
    width=273.0,
    height=44.0
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    196.5,
    267.0,
    image=entry_image_3
)
entry_3 = Entry(
    bd=0,
    bg="#CA3D3D",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=78.0,
    y=244.0,
    width=237.0,
    height=44.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    196.5,
    172.0,
    image=entry_image_4
)
entry_4 = Entry(
    bd=0,
    bg="#CA3D3D",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=78.0,
    y=149.0,
    width=237.0,
    height=44.0
)

canvas.create_text(
    36.0,
    112.0,
    anchor="nw",
    text="Date:",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 30 * -1)
)

canvas.create_text(
    39.0,
    209.0,
    anchor="nw",
    text="Category:",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 30 * -1)
)

canvas.create_text(
    55.0,
    399.0,
    anchor="nw",
    text="Description",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 30 * -1)
)

canvas.create_text(
    33.0,
    304.0,
    anchor="nw",
    text="Amount:",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 30 * -1)
)

canvas.create_text(
    229.0,
    33.0,
    anchor="nw",
    text="New Expense",
    fill="#FFFFFF",
    font=("JosefinSans Medium", 50 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    566.0,
    256.0,
    image=image_image_1
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=233.0,
    y=506.0,
    width=333.814697265625,
    height=60.0
)
window.resizable(False, False)
window.mainloop()
