# This Gui file was generated by the Tkinter Designer by Parth Jadhav and modified by Justin Gomez
# Design made by Justin Gomez
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Frame, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH_FRAME1 = OUTPUT_PATH / "assets" / "frame1"

def relative_to_assets_income_frame(path: str) -> str:
    return str(ASSETS_PATH_FRAME1 / path)


class IncomeFrame(Frame):
    def __init__(self, master, return_callback):
        super().__init__(master, bg="#2E2E2E")
        self.configure(bg="#2E2E2E")
        self.canvas = Canvas(
            self,
            bg = "#2E2E2E",
            height = 600,
            width = 800,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        self.canvas.pack(fill="both", expand=True)

        self.entry_image_1 = PhotoImage(
            file=relative_to_assets_income_frame("entry_1.png"))
        self.entry_bg_1 = self.canvas.create_image(
            394.5,
            463.0,
            image=self.entry_image_1
        )
        self.entry_1 = Entry(
            self,
            bd=0,
            bg="#24A228",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_1.place(
            x=78.0,
            y=440.0,
            width=633.0,
            height=44.0
        )

        self.entry_image_2 = PhotoImage(
            file=relative_to_assets_income_frame("entry_2.png"))
        self.entry_bg_2 = self.canvas.create_image(
            214.5,
            364.0,
            image=self.entry_image_2
        )
        self.entry_2 = Entry(
            self,
            bd=0,
            bg="#24A228",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_2.place(
            x=78.0,
            y=341.0,
            width=273.0,
            height=44.0
        )

        self.entry_image_3 = PhotoImage(
            file=relative_to_assets_income_frame("entry_3.png"))
        self.entry_bg_3 = self.canvas.create_image(
            196.5,
            269.0,
            image=self.entry_image_3
        )
        self.entry_3 = Entry(
            self,
            bd=0,
            bg="#24A228",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_3.place(
            x=78.0,
            y=246.0,
            width=237.0,
            height=44.0
        )

        self.entry_image_4 = PhotoImage(
            file=relative_to_assets_income_frame("entry_4.png"))
        self.entry_bg_4 = self.canvas.create_image(
            196.5,
            174.0,
            image=self.entry_image_4
        )
        self.entry_4 = Entry(
            self,
            bd=0,
            bg="#24A228",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_4.place(
            x=78.0,
            y=151.0,
            width=237.0,
            height=44.0
        )

        self.canvas.create_text(
            36.0,
            114.0,
            anchor="nw",
            text="Date:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 30 * -1)
        )

        self.canvas.create_text(
            39.0,
            211.0,
            anchor="nw",
            text="Category:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 30 * -1)
        )

        self.canvas.create_text(
            55.0,
            401.0,
            anchor="nw",
            text="Description",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 30 * -1)
        )

        self.canvas.create_text(
            33.0,
            306.0,
            anchor="nw",
            text="Amount:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 30 * -1)
        )

        self.canvas.create_text(
            248.0,
            36.0,
            anchor="nw",
            text="New Income",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 50 * -1)
        )

        self.image_image_1 = PhotoImage(
            file=relative_to_assets_income_frame("image_1.png"))
        self.image_1 = self.canvas.create_image(
            592.0,
            269.0,
            image=self.image_image_1
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets_income_frame("button_1.png"))
        self.button_1 = Button(
            self,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat"
        )
        self.button_1.place(
            x=233.0,
            y=508.0,
            width=333.814697265625,
            height=60.0
        )

        # Back button
        self.back_button = Button(self, text="Back", command=return_callback)
        self.back_button.place(x=10, y=10)