# This Gui file was generated by the Tkinter Designer by Parth Jadhav and modified by Justin Gomez
# Design made by Justin Gomez
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Frame, Canvas, Entry, Text, Button, PhotoImage
from income_frame import IncomeFrame
from expenses_frame import ExpensesFrame

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH_FRAME0 = OUTPUT_PATH / "assets" / "frame0"

def relative_to_assets_frame0(path: str) -> str:
    return str(ASSETS_PATH_FRAME0 / path)

class MainWindow(Tk):
    def __init__(self):
        super().__init__()
        self.geometry("800x600")
        self.configure(bg="#2E2E2E")
        self.title("Expenses Tracker")
        self.main_frame = Frame(self, bg="#2E2E2E")
        self.main_frame.pack(fill="both", expand=True)

        # Canvas Setup ------------------------------------------------------------------------
        self.main_canvas = Canvas(
            self.main_frame,
            bg = "#2E2E2E",
            height = 600,
            width = 800,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        self.main_canvas.place(x = 0, y = 0)

        # Header Text -------------------------------------------------------------------------
        self.main_canvas.create_text(
            215.0,
            15.0,
            anchor="nw",
            text="EXPENSES TRACKER",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 35 * -1)
        )

        # Income Components ---------------------------------------------------------------------
        self.bg_income = PhotoImage(
            file=relative_to_assets_frame0("bg_income.png"))
        income_background = self.main_canvas.create_image(
            227.0,
            105.0,
            image=self.bg_income
        )

        self.main_canvas.create_text(
            120.0,
            80.0,
            anchor="nw",
            text="Income:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 25 * -1)
        )
        self.income_text = self.main_canvas.create_text(
            240.0,
            77.0,
            anchor="nw",
            text="$0.00",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 35 * -1)
        )

        # Expenses Components -------------------------------------------------------------------
        self.bg_expenses = PhotoImage(
            file=relative_to_assets_frame0("bg_expenses.png"))
        self.expenses_background = self.main_canvas.create_image(
            572.0,
            105.0,
            image=self.bg_expenses
        )
        self.main_canvas.create_text(
            460.0,
            80.0,
            anchor="nw",
            text="Expenses:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 25 * -1)
        )
        self.expenses_text = self.main_canvas.create_text(
            600.0,
            77.0,
            anchor="nw",
            text="$0.00",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 35 * -1)
        )



        # Balance Components ------------------------------------------------------------------
        self.bg_balance = PhotoImage(
            file=relative_to_assets_frame0("bg_balance.png"))
        self.balance_background = self.main_canvas.create_image(
            400.0,
            180.0,
            image=self.bg_balance
        )

        self.main_canvas.create_text(
            250.0,
            155.0,
            anchor="nw",
            text="Balance:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 30 * -1)
        )
        self.balance_text = self.main_canvas.create_text(
            425.0,
            152.0,
            anchor="nw",
            text="$0.00",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 40 * -1)
        )



        # Image -----------------------------------------------------------------------------------
        self.image_image_4 = PhotoImage(
            file=relative_to_assets_frame0("image_4.png"))
        self.image_4 = self.main_canvas.create_image(
            214.0,
            399.0,
            image=self.image_image_4
        )




        # Buttons: New income, expense, and history ------------------------------------------------
        # New Income Button
        self.income_button_image = PhotoImage(
            file=relative_to_assets_frame0("button_new_income.png"))

        self.new_income_button = Button(
            self.main_canvas,
            image=self.income_button_image,
            borderwidth=0,
            highlightthickness=0,
            command=self.open_income_canvas,  # Open gui1.py when clicked
            #command=lambda: print("button_1 clicked"),  # For testing
            relief="flat",
            bg="#2E2E2E",
            activebackground="#2E2E2E"
        )

        self.new_income_button.place(
            x=425.0,
            y=277.0,
        )


        # New Expense Button
        self.expense_button_image = PhotoImage(
            file=relative_to_assets_frame0("button_new_expense.png"))
        self.new_expense_button = Button(
            self.main_canvas,
            image=self.expense_button_image,
            borderwidth=0,
            highlightthickness=0,
            command=self.open_expense_canvas,  # Open gui2.py when clicked),
            relief="flat",
            bg="#2E2E2E",
            activebackground="#2E2E2E"
        )
        self.new_expense_button.place(
            x=425.0,
            y=366.0,
        )


        # History Button
        self.history_button_image = PhotoImage(
            file=relative_to_assets_frame0("button_history.png"))
        self.history_button = Button(
            self.main_canvas,
            image=self.history_button_image,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            relief="flat",
            bg="#2E2E2E",
            activebackground="#2E2E2E"
        )
        self.history_button.place(
            x=425.0,
            y=451.0,
        )

        # Income Frame Setup -------------------------------------------------------------------
        self.income_frame = IncomeFrame(self, self.return_to_main)  # Create the frame
        self.expense_frame = ExpensesFrame(self, self.return_to_main)  # Create the expense frame

        
    def open_income_canvas(self):
        self.main_frame.pack_forget()
        self.income_frame.pack(fill="both", expand=True)

    def open_expense_canvas(self):
        self.main_frame.pack_forget()
        self.expense_frame.pack(fill="both", expand=True)

    def return_to_main(self):
        self.income_frame.pack_forget()
        self.expense_frame.pack_forget()
        self.main_frame.pack(fill="both", expand=True)
        # Update the income balance text
        # main_canvas.itemconfig(income_balance, text="$0.00")  # Example update, replace with actual logic