# This Gui file was generated by the Tkinter Designer by Parth Jadhav and modified by Justin Gomez
# Design made by Justin Gomez
# https://github.com/ParthJadhav/Tkinter-Designer

from pathlib import Path
from tkinter import Tk, Frame, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH_FRAME1 = OUTPUT_PATH / "assets" / "frame1"

def relative_to_assets_income_frame(path: str) -> str:
    return str(ASSETS_PATH_FRAME1 / path)


class IncomeFrame(Frame):
    def __init__(self, master, return_callback):
        super().__init__(master, bg="#2E2E2E")
        self.configure(bg="#2E2E2E")
        self.canvas = Canvas(
            self,
            bg = "#2E2E2E",
            height = 600,
            width = 800,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )
        self.canvas.pack(fill="both", expand=True)

        # Header Text -----------------------------------------------------------------
        self.canvas.create_text(
            248.0,
            36.0,
            anchor="nw",
            text="New Income",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 50 * -1)
        )

        # Date Components -------------------------------------------------------------
        self.entry_4 = Entry(
            self,
            bd=0,
            bg="#27732a",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_4.place(
            x=60.0,
            y=140.0,
            width=300.0,
            height=50.0
        )        
        self.canvas.create_text(
            60.0,
            100.0,
            anchor="nw",
            text="Date:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 30 * -1)
        )
        # Category Components ----------------------------------------------------------
        self.entry_3 = Entry(
            self,
            bd=0,
            bg="#27732a",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_3.place(
            x=60.0,
            y=240.0,
            width=300.0,
            height=50.0
        )
        self.canvas.create_text(
            60.0,
            200.0,
            anchor="nw",
            text="Category:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 30 * -1)
        )

        # Amount Components --------------------------------------------------------------
        self.entry_2 = Entry(
            self,
            bd=0,
            bg="#27732a",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_2.place(
            x=60.0,
            y=340.0,
            width=300.0,
            height=50.0
        )
        self.canvas.create_text(
            60.0,
            300.0,
            anchor="nw",
            text="Amount:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 30 * -1)
        )

        # Description Components ----------------------------------------------------------
        self.entry_1 = Entry(
            self,
            bd=0,
            bg="#27732a",
            fg="#000716",
            highlightthickness=0
        )
        self.entry_1.place(
            x=60.0,
            y=440.0,
            width=650.0,
            height=50.0
        )
        self.canvas.create_text(
            60.0,
            400.0,
            anchor="nw",
            text="Description:",
            fill="#FFFFFF",
            font=("JosefinSans Medium", 30 * -1)
        )


        

        self.image_image_1 = PhotoImage(
            file=relative_to_assets_income_frame("image_1.png"))
        self.image_1 = self.canvas.create_image(
            592.0,
            269.0,
            image=self.image_image_1
        )

        self.button_image_1 = PhotoImage(
            file=relative_to_assets_income_frame("button_1.png"))
        self.button_1 = Button(
            self,
            image=self.button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_1 clicked"),
            relief="flat",
            bg="#2E2E2E",
            activebackground="#2E2E2E"
        )
        self.button_1.place(
            x=233.0,
            y=508.0,
            width=333.814697265625,
            height=60.0
        )

        # Back button
        self.back = PhotoImage(
            file=relative_to_assets_income_frame("back_button.png"))
        self.back_button = Button(
            self,
            image=self.back,
            borderwidth=0,
            highlightthickness=0,
            command=return_callback,
            relief="flat",
            bg="#2E2E2E",
            activebackground="#2E2E2E"
        )
        self.back_button.place(
            x=30.0,
            y=30.0,
        )